/* =========================================================
   Stock Quantities
   Each value is the number of units currently in stock (0 = out of stock).

   HOW THIS WORKS (important — this is a frontend-only site with
   no server/database):
   - This file (STOCK below) is the "official" stock list every
     visitor's browser loads.
   - The Admin Panel (admin.html) lets you add stock or set exact
     quantities per item. Changes apply INSTANTLY on the same
     browser/device via local storage, so you can preview them right
     away on the Products page.
   - To make a stock change visible to every customer (not just your
     own browser), click "Download stock.js" in the Admin Panel and
     replace this file with the downloaded one wherever the site is
     hosted. Until you do that, other visitors still see the values
     below.
   ========================================================= */

const STOCK = {
  p01: 50,
  p02: 50,
  p03: 50,
  p04: 50,
  p05: 50,
  p06: 50,
  p07: 50,
  p08: 50,
  p09: 50,
  p10: 50,
  p11: 50,
  p12: 50,
  p13: 50,
  p14: 50,
  p15: 50,
};

const STOCK_OVERRIDE_KEY = "fw_stock_override";

/** Items at or below this quantity are treated as "running low" across
    the site (Products page badge, Bulk Stock Update warnings, etc). */
const LOW_STOCK_THRESHOLD = 10;

function getStockOverrides(){
  try{ return JSON.parse(localStorage.getItem(STOCK_OVERRIDE_KEY)) || {}; }
  catch(e){ return {}; }
}

/** Sets the ABSOLUTE quantity for a product (local preview override). */
function setStockOverride(id, qty){
  const overrides = getStockOverrides();
  overrides[id] = Math.max(0, Number(qty) || 0);
  localStorage.setItem(STOCK_OVERRIDE_KEY, JSON.stringify(overrides));
}

/** Effective quantity for a product: local preview override wins,
    otherwise falls back to the deployed STOCK data above. */
function getStockQty(id){
  const overrides = getStockOverrides();
  if(Object.prototype.hasOwnProperty.call(overrides, id)) return Math.max(0, Number(overrides[id]) || 0);
  if(Object.prototype.hasOwnProperty.call(STOCK, id)) return Math.max(0, Number(STOCK[id]) || 0);
  return 0;
}

/** Adds `amount` units to a product's current quantity (restocking). */
function addStockQty(id, amount){
  const newQty = getStockQty(id) + Math.max(0, Number(amount) || 0);
  setStockOverride(id, newQty);
  return newQty;
}

/** A product is in stock as long as its quantity is above zero. */
function isInStock(id){
  return getStockQty(id) > 0;
}

/** Merges STOCK + any local overrides into one map — used by the admin page. */
function getEffectiveStockMap(){
  const overrides = getStockOverrides();
  return { ...STOCK, ...overrides };
}

/** Builds the full text of an updated stock.js file reflecting current
    (STOCK + overrides) values, ready to download and redeploy. */
function buildStockFileContents(){
  const map = getEffectiveStockMap();
  const lines = Object.keys(map).map(id => `  ${id}: ${Math.max(0, Number(map[id]) || 0)},`).join("\n");
  return `/* =========================================================
   Stock Quantities
   Each value is the number of units currently in stock (0 = out of stock).
   Generated by the Admin Panel — replace js/stock.js on your hosting
   with this file to make these changes visible to every visitor.
   ========================================================= */

const STOCK = {
${lines}
};

const STOCK_OVERRIDE_KEY = "fw_stock_override";

function getStockOverrides(){
  try{ return JSON.parse(localStorage.getItem(STOCK_OVERRIDE_KEY)) || {}; }
  catch(e){ return {}; }
}

function setStockOverride(id, qty){
  const overrides = getStockOverrides();
  overrides[id] = Math.max(0, Number(qty) || 0);
  localStorage.setItem(STOCK_OVERRIDE_KEY, JSON.stringify(overrides));
}

function getStockQty(id){
  const overrides = getStockOverrides();
  if(Object.prototype.hasOwnProperty.call(overrides, id)) return Math.max(0, Number(overrides[id]) || 0);
  if(Object.prototype.hasOwnProperty.call(STOCK, id)) return Math.max(0, Number(STOCK[id]) || 0);
  return 0;
}

function addStockQty(id, amount){
  const newQty = getStockQty(id) + Math.max(0, Number(amount) || 0);
  setStockOverride(id, newQty);
  return newQty;
}

function isInStock(id){
  return getStockQty(id) > 0;
}

function getEffectiveStockMap(){
  const overrides = getStockOverrides();
  return { ...STOCK, ...overrides };
}
`;
}